### ISSUE TITLE
Tests and CI scripts

### ISSUE THREAD

**Issue by Luni-4** [sifis-home/privacydashboard#1]
This list shows the necessary tasks to be performed in order to be compliant with the SIFIS-Home specifications, feel free to ping me if you need some help @Finevman

- [x] Does the project have a `README.md` that explains how this software works ?
- [x] Does the project have a `LICENSE` file? 
    - **Copy this [License](https://github.com/sifis-home/ace-entities/blob/master/LICENSE.md)**
    - If possible use either [MIT](https://spdx.org/licenses/MIT) or other compatible licenses. 
- [x] Does the project have a [GitHub Action](https://github.com/features/actions) (you may use [sifis-generate](https://crates.io/crates/sifis-generate) to create it)?
   - **Copy this [CI](https://github.com/sifis-home/ace-entities/blob/master/.github/workflows/github.yml) script adapting it to your needs**
   - [x] Does it upload the code coverage somewhere? 
   -  **Contained in the script above**
   - [x] Does it manage the release of the code? (Continuous Delivery) 
   - **Have a look at this [CI](https://github.com/sifis-home/ace-entities/blob/master/.github/workflows/deploy.yml) script**
- [x] Does it have a DockerFile or does it need it? 
    - **Contained in this [CI](https://github.com/sifis-home/ace-entities/blob/master/.github/workflows/github.yml) script**

**Comment by Finevman** [comment]
@Luni-4 
Does the README have to explain the software at high level (i.e. User interactions on the front end) or at low level (actual inner workings)?

**Comment by Luni-4** [comment]
@Finevman 
User interactions and developers guidelines (how to build and run it, what dependencies are needed and so on), everything that could be useful for a user and a developer practically

**Comment by Finevman** [comment]
The code coverage is compiled and stored in the target/site/jacoco/index.html file.

**Comment by Luni-4** [comment]
@Finevman 
Use the same structure of the advised CI scripts and then change accordingly to the project if they do not work

**Comment by Finevman** [comment]
@Luni-4 Do I need to make the "Docker build push" job of the Action work or it is sufficient for the image to be built correctly?

**Comment by Finevman** [comment]
@Luni-4 What files exactly do I need to zip for the release? I created the .jar but it could not load properly. That is why, at the moment, I am zipping the .class files together with the vaadin files, but that can be changed pretty easily.

**Comment by Luni-4** [comment]
@Finevman 
It would be better to load the `.jar` file, so anyone can download it and run on its machine. Can you try this  [approach](https://github.com/sifis-home/ace-entities/blob/master/.github/workflows/deploy.yml#L41-L47)? It should load a `.jar` file if it is zipped

**Comment by Luni-4** [comment]
As last step to close this issue, we need to increase code coverage to 60%
